
CREATE TABLE ENDERECO(
	ID_ENDERECO INTEGER,
	CEP INTEGER,
	LOGRADOURO VARCHAR,
	NUMERO VARCHAR,
	BAIRRO VARCHAR,
	CIDADE VARCHAR,
	ESTADO VARCHAR,
	CONSTRAINT PK_ENDERECOS PRIMARY KEY (ID_ENDERECO)
	);

CREATE TABLE TELEFONES(
    ID_TELEFONE INTEGER,
    DDD INTEGER,
    NUMERO INTEGER,
    ID_CONTATO INTEGER,
    CONSTRAINT PK_TELEFONES PRIMARY KEY (ID_TELEFONE),
    CONSTRAINT FK_CONTATO_TELEFONES FOREIGN KEY (ID_CONTATO) REFERENCES CONTATOS (ID_CONTATO)
)
CREATE TABLE CONTATOS(
	ID_CONTATO INTEGER,
	EMAIL VARCHAR,
	CONSTRAINT PK_CONTATOS PRIMARY KEY (ID_CONTATO)
	);
	
CREATE TABLE PACIENTES(
	ID_PACIENTE INTEGER,
	NOME VARCHAR,
	CPF BIGINT,
	RG BIGINT,
	DATANASC DATE,
	ID_CONTATO INTEGER,
	ID_ENDERECO INTEGER,
	CONSTRAINT PK_PACIENTES PRIMARY KEY (ID_PACIENTE),
	CONSTRAINT FK_CONTATO_PACIENTES FOREIGN KEY (ID_CONTATO) REFERENCES CONTATOS (ID_CONTATO),
	CONSTRAINT FK_ENDERECO_PACIENTES FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECOS (ID_ENDERECO)
	);

CREATE TABLE FUNCIONARIOS(
	ID_FUNCIONARIO INTEGER,
	NOME VARCHAR,
	CPF BIGINT,
	RG BIGINT,
	ID_CONTATO INTEGER,
	ID_ENDERECO INTEGER,
    TIPO INTEGER,
	CONSTRAINT PK_FUNCIONARIOS PRIMARY KEY (ID_FUNCIONARIO),
	CONSTRAINT FK_CONTATO_FUNCIONARIOS FOREIGN KEY (ID_CONTATO) REFERENCES CONTATOS (ID_CONTATO),
	CONSTRAINT FK_ENDERECO_FUNCIONARIOS FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECOS (ID_ENDERECO)
	);

CREATE TABLE ESPECIALIDADES(
	ID_ESPECIALIDADE INTEGER,
	NOME VARCHAR,
	CONSTRAINT PK_ESPECIALIDADES PRIMARY KEY (ID_ESPECIALIDADE)
	);

CREATE TABLE MEDICOS(
	CRM INTEGER UNIQUE,
	ID_FUNCIONARIO INTEGER,
	ID_ESPECIALIDADE INTEGER,
	CONSTRAINT PK_MEDICOS PRIMARY KEY (CRM),
	CONSTRAINT FK_FUNCIONARIOS_MEDICOS FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIOS (ID_FUNCIONARIO),
	CONSTRAINT FK_ESPECIALIDADES_MEDICOS FOREIGN KEY (ID_ESPECIALIDADE) REFERENCES ESPECIALIDADES (ID_ESPECIALIDADE)
	);


CREATE TABLE LOGINS_PACIENTES(
	ID_LOGIN INTEGER,
	EMAIL VARCHAR,
	SENHA VARCHAR,
	ID_PACIENTE,
	CONSTRAINT PK_LOGINS_PACIENTES PRIMARY KEY (ID_LOGIN),
	CONSTRAINT FK_PACIENTES_LOGINS FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES (ID_PACIENTE)
	);

CREATE TABLE LOGINS_FUNCIONARIOS(
	ID_LOGIN INTEGER,
	EMAIL VARCHAR,
	SENHA VARCHAR,
	ID_FUNCIONARIO INTEGER,
	PERMISSAO VARCHAR,
	CONSTRAINT PK_LOGINS_FUNCIONARIOS PRIMARY KEY (ID_LOGIN).
	CONSTRAINT FK_FUNCIONARIOS_LOGINS FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIOS (ID_FUNCIONARIO)
	);

CREATE TABLE AGENDAS_MEDICAS(
	ID_AGENDA_MEDICA INTEGER,
	DATA_AGENDA DATE,
	HORARIO_INICIO TIME,
	HORARIO_FIM TIME,
	TEMPO_ATENDIMENTO TIME,
	ID_FUNCIONARIO INTEGER,
	ID_MEDICO INTEGER,
	ID_ESPECIALIDADE INTEGER,
	CONSTRAINT PK_AGENDAS_MEDICAS PRIMARY KEY (ID_AGENDA_MEDICA),
	CONSTRAINT FK_FUNCIONARIOS_AGENDAS_MEDICAS FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIOS (ID_FUNCIONARIO),
	CONSTRAINT FK_MEDICOS_AGENDAS_MEDICAS FOREIGN KEY (ID_MEDICO) REFERENCES MEDICOS (ID_MEDICO),
	CONSTRAINT FK_ESPECIALIDADES_AGENDAS_MEDICAS FOREIGN KEY (ID_ESPECIALIDADE) REFERENCES ESPECIALIDADES (ID_ESPECIALIDADE)
	);
	
CREATE TABLE CONSULTAS(
	ID_AGENDAMENTO INTEGER,
	ID_PACIENTE INTEGER,
	ID_MEDICO INTEGER,
	ID_FUNCIONARIO INTEGER,
	ID_ESPECIALIDADE INTEGER,
	DATA_AGENDAMENTO DATE,
	HORARIO TIME,
	CONSTRAINT PK_AGENDAMENTOS PRIMARY KEY (ID_AGENDAMENTO),
	CONSTRAINT FK_PACIENTES_AGENDAMENTOS FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES (ID_PACIENTES),
	CONSTRAINT FK_FUNCIONARIOS_AGENDAMENTOS FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIOS (ID_FUNCIONARIO),
	CONSTRAINT FK_MEDICOS_AGENDAMENTOS FOREIGN KEY (ID_MEDICO) REFERENCES MEDICOS (ID_MEDICO),
	CONSTRAINT FK_ESPECIALIDADES_AGENDAMENTOS FOREIGN KEY (ID_ESPECIALIDADE) REFERENCES ESPECIALIDADES (ID_ESPECIALIDADE)
	);